name: "nyc_taxi"
version: "1.0.0"
config-version: 2

profile: "nyc_taxi"

model-paths:
  - "models"

models:
  nyc_taxi:
    staging:
      +schema: staging
      +materialized: view

    intermediate:
      +schema: intermediate
      +materialized: view

    marts:
      +schema: analytics
      +materialized: table