services:
  airflow:
    restart: "no"

    build:
      context: .
      dockerfile: airflow/Dockerfile

    container_name: nyc-taxi-airflow

    user: "${AIRFLOW_UID}:0"

    command: standalone

    ports:
      - "8080:8080"

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./src:/opt/airflow/project/src
      - ./dbt:/opt/airflow/project/dbt
      - ./data:/opt/airflow/project/data

    depends_on:
      - postgres

  postgres:
    restart: "no"

    image: postgres:18

    container_name: nyc-taxi-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/18/docker


volumes:
  postgres_data:
